config/routes.rb
Rails.application.routes.draw do

  namespace :admins_backoffice do
    get 'welcome/index' #index ADMIN
    resources :members #Membros
    resources :addresses #Endereços
    resources :positions #Cargos
    resources :churches #Igrejas
  end
  devise_for :users
  namespace :site do
    get 'welcome/index'
  end
  
  root to: 'site/welcome#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :member
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/church.rb
class Church < ApplicationRecord
  has_many :member
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :position
  belongs_to :church
  has_one :address

end

app/models/position.rb
class Position < ApplicationRecord
  has_many :member
end

app/models/user.rb
class User < ApplicationRecord

  enum role: [:normal_user, :admin, :moderator, :umademmfs, :cibefs]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/members_controller.rb
class AdminsBackoffice::MembersController < AdminsBackofficeController

  before_action :set_positions_options, only: [:new, :create, :edit, :update]
  before_action :set_churches_options, only: [:new, :create, :edit, :update]
  before_action :set_member, only: [:edit, :update, :destroy]

  def index
    @members = Member.all
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(params_member)
    if @member.save
      redirect_to admins_backoffice_members_path, notice: "Membro cadastrado com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @member.update(params_member)
      redirect_to admins_backoffice_members_path, notice: "Membro atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @member.destroy
      redirect_to admins_backoffice_members_path, notice: "Membro exluído com sucesso!"
    else
      render :index
    end
  end

  private
  
  def params_member
    params_member = params.require(:member).permit(:num_member ,:name, :rg, :date_birth, :sex, 
                                                  :date_baptism, :phone, :position_id, 
                                                  :church_id, addresses_atributes: 
                                                  [:id, :street, :neighborhood, :number, 
                                                  :zip_code, :complement, :city,
                                                  :state])
  end

  def set_member
    @member = Member.find(params[:id])
  end

  def set_positions_options
    @positions_options = Position.all.pluck( :description, :id )
  end
  
  def set_churches_options
    @churches_options = Church.all.pluck( :description, :id )
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
    @users = User.all
    authorize @users
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_user!
  layout 'layout_admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

private

  def user_not_authorized
    flash[:notice] = "Você não tem permissão para acessar essa pagina."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
    @users = User.all
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'layout_site'
end

app/helpers/admins_backoffice/members_helper.rb
module AdminsBackoffice::MembersHelper

end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object = nil, method = nil)
    (object && method) ? object.model.human_attribute_name(method) : "Informe os parâmetros corretamente"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/admins_backoffice/members/edit.html.erb
<%= render partial: 'admins_backoffice/members/shared/form',
  locals: { action_message: t('messages.editing', model: @member.model_name.human) } %>

app/views/admins_backoffice/members/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t('messages.listing', model: @members.model_name.human(count: 2)) %></h1>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th><%= translate_attribute(@members, :num_member) %></th>
        <th><%= translate_attribute(@members, :name) %></th>
        <th><%= translate_attribute(@members, :phone) %></th>
        <th><%= translate_attribute(@members, :position) %></th>
        <th><%= translate_attribute(@members, :church) %></th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td style="width: 150px"><%= member.num_member %></td>
          <td><%= member.name %></td>
          <td style="width: 100px"><%= member.phone %></td>
          <td><%= member.position.description %></td>
          <td><%= member.church.description %></td>
          <td style="width: 115px">
            <%= link_to edit_admins_backoffice_member_path(member), class:'btn btn-success btn-circle',
            data: {toggle:"tooltip", placement:"bottom"},  title:"Visualizar" do %>
              <i class="fa fa-list-alt"></i>
            <% end %>
            <%= link_to edit_admins_backoffice_member_path(member), class:'btn btn-primary btn-circle',
            data: {toggle:"tooltip", placement:"bottom"},  title:"Editar" do %>
              <i class="fa fa-edit"></i>
            <% end %>
            <%= link_to admins_backoffice_member_path(member), method: :delete, class:"btn btn-danger btn-circle",
            data: { confirm: t('messages.confirm_with'), toggle:"tooltip", placement:"bottom" }, title:"Apagar"  do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins_backoffice/members/new.html.erb
<%= render partial: 'admins_backoffice/members/shared/form',
  locals: { action_message: t('messages.new', model: @member.model_name.human) } %>

app/views/admins_backoffice/members/shared/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= action_message %></h1>
  </div>
</div>
<div class="row">
  <% if @member.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <ul>
      <% @member.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end%>
    </ul>
  </div>
  <% end %>
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading"><%= "#{action_message}" %></div>
      <div class="panel-body">
        <div class="justify-content-center mb-5">
          <div class="col-sm-12 col-md-10 col-lg-12">
            <%= form_with(model: [:admins_backoffice, @member], local: true) do |form| %>
              <div class="form-row">
                <div class="form-group col-sm-3">
                  <%= form.label :num_member %>
                  <%= form.text_field :num_member, class:'form-control', placeholder:"Número do membro" %>
                </div>
                <div class="form-group col-sm-5">
                  <%= form.label :name %>
                  <%= form.text_field :name, class:'form-control', placeholder:"Nome Completo do membro" %>
                </div>
                <div class="form-group col-sm-4">
                  <%= form.label :rg %>
                  <%= form.text_field :rg, class:'form-control', placeholder:"Número da identidade" %>
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-sm-3">
                  <%= form.label :date_birth %>
                  <%= form.date_field :date_birth, class:'form-control', placeholder:"Data de nascimento do membro" %>
                </div>
                <div class="form-group col-sm-3">
                  <%= form.label :date_baptism %>
                  <%= form.date_field :date_baptism, class:'form-control', placeholder:"Data de batismo do membro" %>
                </div>
                <div class="form-group col-sm-3">
                  <%= form.label :sex %>
                  <%= form.select :sex, ['Masculino', 'Feminino'], { include_blank: 'Selecione...' }, class:"form-control" %>
                </div>
                <div class="form-group col-sm-3">
                  <%= form.label :phone %>
                  <%= form.text_field :phone, class:'form-control', placeholder:"Telefone do membro" %>
                </div>
              </div>
              <div class="group-row">
                <div class="form-group col-sm-6">
                  <%= form.label :church %>
                  <%= form.select( "church_id", @churches_options, { include_blank: 'Selecione...' }, class:"form-control") %>
                </div>
                <div class="form-group col-sm-6">
                  <%= form.label :position %>
                  <%= form.select( "position_id", @positions_options, { include_blank: 'Selecione...' }, class:"form-control") %>
                </div>
              </div>
              <%= form.fields_for :addresses do |f| %>
                <div class="form-row">
                  <div class="form-group col-sm-3">
                    <%= f.label :street %>
                    <%= f.text_field :street, class:'form-control', placeholder:"Rua" %>
                  </div>
                  <div class="form-group col-sm-5">
                    <%= f.label :neighborhood %>
                    <%= f.text_field :neighborhood, class:'form-control', placeholder:"Bairro" %>
                  </div>
                  <div class="form-group col-sm-4">
                    <%= f.label :number %>
                    <%= f.text_field :number, class:'form-control', placeholder:"Número" %>
                  </div>
                </div>
                <div class="form-row">
                  <div class="form-group col-sm-3">
                    <%= f.label :complement %>
                    <%= f.text_field :complement, class:'form-control', placeholder:"Complemento" %>
                  </div>
                  <div class="form-group col-sm-3">
                    <%= f.label :zip_code %>
                    <%= f.text_field :zip_code, class:'form-control', placeholder:"CEP" %>
                  </div>
                  <div class="form-group col-sm-3">
                    <%= f.label :city %>
                    <%= f.text_field :city, class:'form-control', placeholder:"Cidade" %>
                  </div>
                  <div class="form-group col-sm-3">
                    <%= f.label :state %>
                    <%= f.text_field :state, class:'form-control', placeholder:"Estado" %>
                  </div>
                </div>
              <% end %>
              <div class="form-row">
                <div class="col-sm-12">
                  <button type="submit" class="btn btn-success">Salvar</button>
                </div>
              </div>
            <% end %>
          </div>
        </div>                
      </div>
    </div>
  </div>
</div>

app/views/admins_backoffice/welcome/index.html.erb
<h1>Bem vindo a pagina do administrador</h1>
<p>Verifique a barra lateral esquerda, para ver o que você pode fazer.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SiteIgreja</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/layout_admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Igreja Assembleia de Deus - Ministerio de Madureira - Feira de Santana - BA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'layout_admin' %>
    <%= favicon_link_tag asset_path('logo') %>
  </head>

  <body>
    <div id="wrapper">
      <!-- Navigation -->
      <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Menu</span>
            <i class="fa fa-navicon"></i>
          </button>
          <%= link_to 'ADEMMFS - Administrador', admins_backoffice_welcome_index_path, class:'navbar-brand' %>
        </div>
        <!-- /.navbar-header -->
        <ul class="nav navbar-top-links navbar-right">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="fa fa-user fa-fw"></i> <%= current_user.name %> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out fa-fw"></i> Sair
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
        <div class="navbar-default sidebar" role="navigation">
          <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
              <li>
                <%= link_to admins_backoffice_welcome_index_path, class:"active" do %>
                  <i class="fa fa-home"></i> Inicio
                <% end %>
              </li>
              <li class="active">
                <a href="#"><i class="fa fa-users"></i> Membros<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse in" aria-expanded="true">
                  <li>
                    <%= link_to 'Listar Membros', admins_backoffice_members_path %>
                  </li>
                  <li>
                    <%= link_to 'Cadastrar novo Membro', new_admins_backoffice_member_path %>
                  </li>
                </ul>
              </li>
              <li>
                <%= link_to site_welcome_index_path do %>
                  <i class="fa fa-arrow-left"></i> Voltar para o site
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div id="page-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
    

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'layout_admin' %>

  <% if notice %>
    <%= javascript_tag do %>
      $.bootstrapGrowl('<%= notice %>', {
      type: 'success',
      align: 'right',
      allow_dismiss: true,
      stackup_spacing: 10
    });
    <% end %>
  <% end %>

  </body>
</html>

app/views/layouts/layout_site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Igreja Assembleia de Deus - Ministerio de Madureira - Feira de Santana - BA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'layout_site' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <%= favicon_link_tag asset_path('logo') %>
  </head>
  <body id="page-top">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
          <div class="row">
            <%= link_to site_welcome_index_path, class:'navbar-brand js-scroll-trigger' do %>
              <%= image_tag 'logo', width: 50, height: 50 %> Assembleia de Deus
            <% end %>
          </div>
          <button class="navbar-toggler navbar-toggler-right ml-auto" type="button" data-toggle="collapse"
          data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
          aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ml-auto">
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#home">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#programation">programação</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#eventos">Eventos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#about">Sobre nós</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#contact">Pedido de oração</a>
              </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle js-scroll-trigger" href="#" id="navbarDropdown"
                  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Departamentos
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to 'CIBEFS', "#", class:"dropdown-item" %>
                    <%= link_to 'UMADEMMFS', "#", class:"dropdown-item" %>
                    <%= link_to 'UMADEMMFS', "#", class:"dropdown-item" %>
                    <%= link_to 'UMADEMMFS', "#", class:"dropdown-item" %>                                        
                  </div>
                </li>
              <li class="nav-item">
                <% unless user_signed_in? %>
                  <%= link_to 'Login/Registrar', user_session_path, class:'nav-link js-scroll-trigger' %>
                <% else %>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle js-scroll-trigger" href="#" id="navbarDropdown"
                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <%= current_user.name %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <%= link_to 'Perfil', site_welcome_index_path, class:'dropdown-item' %>
                      <% if policy(@users).index? %>
                        <%= link_to 'Area do ADMIN', admins_backoffice_welcome_index_path, class:'dropdown-item' %>
                      <% end %>
                      <%= link_to 'Sair', destroy_user_session_path, method: :delete, class:'dropdown-item' %>
                    </div>
                  </li>
                <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Header -->
    <header class="masthead parallax">
      <div class="container">
        <div class="intro-text">
          <div class="intro-lead-in">Bem vindo ao nosso WebSite</div>
          <div class="intro-heading text-uppercase">Role para baixo para ficar por dentro da nossa programação</div>
          <!--<a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#services">Clique aqui</a>-->
        </div>
      </div>
    </header>

    <%= yield %>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-auto my-2">
            <span class="copyright text-white">
              &copy; 2019 - <%= Time.now.year %>
              Desenvolvido por 
              <%= link_to '#', class:'h6'  do %>
                Marcelo Moreira de Oliveira
              <% end %>
            </span>
          </div>
          <div class="col-md-4 ml-auto">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fab fa-instagram"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.facebook.com/ADEMMFS/">
                  <i class="fab fa-facebook-f"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fab fa-youtube"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    <!-- Portfolio Modals -->

    <!-- Modal 1 -->
    <div class="eventos-modal modal fade" id="eventosModal1" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="close-modal" data-dismiss="modal">
            <div class="lr">
              <div class="rl"></div>
            </div>
          </div>
          <div class="container">
            <div class="row">
              <div class="col-lg-8 mx-auto">
                <div class="modal-body">
                  <!-- Project Details Go Here -->
                  <h2 class="text-uppercase">Project Name</h2>
                  <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                  <img class="img-fluid d-block mx-auto" src="img/portfolio/01-full.jpg" alt="">
                  <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
                  <ul class="list-inline">
                    <li>Date: January 2017</li>
                    <li>Client: Threads</li>
                    <li>Category: Illustration</li>
                  </ul>
                  <button class="btn btn-primary" data-dismiss="modal" type="button">
                    <i class="fas fa-times"></i>
                    Close Project</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'layout_site' %>

  </body>

</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>